
training_id   : 3 # Identifier for the output files from this training
model_type    : 'Bicycle_LSTM' # Bicycle, LSTM, CV, CA, CV_LSTM, CA_LSTM, Bicycle_LSTM
dataset       : 'Fusion' # 'Argoverse', 'NGSIM', 'Fusion'
lstm_feature_size : 128
lstm_n_layers : 1
num_workers   : 16 # how many subprocesses to use for data loading. ``0`` means that the data will be loaded in the main process.
load_name     : 'bicycle_Fusion_37' # Name of the weights file to load, '' for random intitialization
use_nll_loss  : True # Set to True to train with NLL loss False to train with MSE loss
std_threshold : 0.1 # 10cm standard deviation threshold
corr_threshold: 0.01 # x y correlation threshold
n_epochs      : 1000
batch_size    : 32
lr            : 0.0003 # Learning rate
optimizer     : Adam # Adam, Ranger, SGD
print_every_n : 10 # Print the loss and metrics in the terminal every n batch
device        : 'cpu' # 'cpu', 'cuda', '' put '' for default (cuda if available cpu else)
time_pred : 5 # Minimum value between this and the data sequence length will be used
random_rotation : False
random_translation : False
normalize_angle : True


argoverse_data_directory : '../Argoverse/'
#argoverse_data_directory : '../argoverse-api/'
NGSIM_data_directory : '../conv-social-pooling-master/data/'
NGSIM_test_data_directory : './data/'
fusion_data_directory : '../data_fusion/SUV_TF_60kkm/'
